name: PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: oprypin/install-crystal@v1

      - name: Install shards
        run: shards install --ignore-crystal-version

      - name: Check formatting
        run: crystal tool format --check

      - name: Run tests
        run: TZ="Asia/Tokyo" crystal spec
